version: 2

jobs:
  build:
    docker:
      - image: publysher/hugo:0.20
    working_directory: /gregkessman.com

    steps:
      - checkout

      - run:
          name: "Run Hugo"
          command: |
            HUGO_ENV=production hugo -v

      - persist_to_workspace:
          root: /gregkessman.com
          paths: 
            - public/*

  infra:
    working_directory: /gregkessman.com
    docker:
      - image: hashicorp/terraform:0.11.2

    steps:
      - checkout

      - run:
          name: Terraform
          command: sh deploy/infra.sh
  
  deploy:
    docker:
      - image: hashicorp/terraform:0.11.2
    working_directory: /gregkessman.com

    steps:
      - checkout

      - attach_workspace:
          at: /gregkessman.com

      - run:
          name: "S3"
          command: sh deploy/site.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - infra:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - infra
          filters:
            branches:
              only: master